---
name: Deployment

on:
    push:
        tags:
            - "v*.*.*"
            - "[0-9]*.[0-9]*.[0-9]*"

permissions:
    contents: write
    packages: write
    id-token: write
    attestations: write

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

concurrency:
    group: deploy-${{ github.ref }}
    cancel-in-progress: false

jobs:
    prepare:
        name: Prepare
        runs-on: ubuntu-latest
        timeout-minutes: 5
        outputs:
            version: ${{ steps.version.outputs.version }}
            is-prerelease: ${{ steps.version.outputs.is-prerelease }}
        steps:
            - name: Checkout code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

            - name: Determine version
              id: version
              run: |
                  VERSION="${GITHUB_REF#refs/tags/}"
                  VERSION="${VERSION#v}"
                  echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

                  if [[ "${VERSION}" =~ -[a-zA-Z] ]]; then
                      echo "is-prerelease=true" >> "$GITHUB_OUTPUT"
                  else
                      echo "is-prerelease=false" >> "$GITHUB_OUTPUT"
                  fi

    build-and-push:
        name: Build and Push
        runs-on: ubuntu-latest
        needs: prepare
        timeout-minutes: 30
        steps:
            - name: Checkout code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

            - name: Log in to Container Registry
              uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata
              id: meta
              uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                  tags: |
                      type=semver,pattern={{version}}
                      type=semver,pattern={{major}}.{{minor}}
                      type=semver,pattern={{major}},enable=${{ !needs.prepare.outputs.is-prerelease }}
                      type=raw,value=latest,enable=${{ !needs.prepare.outputs.is-prerelease }}

            - name: Build and push Docker image
              id: build
              uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
              with:
                  context: .
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  sbom: true
                  provenance: true

            - name: Generate artifact attestation
              uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3
              with:
                  subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                  subject-digest: ${{ steps.build.outputs.digest }}
                  push-to-registry: true

    release:
        name: Create Release
        runs-on: ubuntu-latest
        needs: [prepare, build-and-push]
        timeout-minutes: 10
        steps:
            - name: Checkout code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

            - name: Extract changelog
              id: changelog
              run: |
                  VERSION="${{ needs.prepare.outputs.version }}"

                  if grep -q "## \[${VERSION}\]" CHANGELOG.md; then
                      awk '/^## \['"${VERSION}"'\]/{flag=1; next} /^## \[.*\]/ && flag {exit} flag' CHANGELOG.md > release_notes.md
                      echo "found=true" >> "$GITHUB_OUTPUT"
                  else
                      echo "Release ${VERSION}" > release_notes.md
                      echo "found=false" >> "$GITHUB_OUTPUT"
                  fi

            - name: Create GitHub Release
              uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2
              with:
                  name: v${{ needs.prepare.outputs.version }}
                  body_path: release_notes.md
                  prerelease: ${{ needs.prepare.outputs.is-prerelease }}
                  generate_release_notes: ${{ steps.changelog.outputs.found == 'false' }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
